### ISSUE TITLE
Filtered length when paginating

### ISSUE THREAD

**Issue by jmorrell** [jmorrell/backbone.obscura#11]
Currently there is no way of knowing how many models are in the collection after filtering if you're also paginating. This is definitely information you may want to show in the UI.

**Comment by jmorrell** [comment]
Perhaps an extension to the paginated collection would be helpful here: `getUnpaginatedLength()` or something along those lines?

**Comment by marcfalk** [comment]
Yep, would totally make sense in my world.

For anyone else stopping by, I'll include the line you posted on Twitter, thanks :)

"proxy._filtered.length" does the trick for now.

**Comment by jmorrell** [comment]
Currently you can access the filtered collection within an obscura collection via `_filtered`, so you can still get access to it.

``` javascript
var proxy = new Obscura(collection);
proxy.filterBy({ a: 2 });
proxy.setPerPage(10);

collection.length; // the original collection length
proxy.length;  //  the paginated length
proxy._filtered.length; // the filtered length
```

Though I'd want an official API for this. Should be simple to add.

**Comment by jmorrell** [comment]
@marcfalk This should be fixed now :)

```
var proxy = new Obscura(collection);
proxy.filterBy({ a: 2 });
proxy.setPerPage(10);

collection.length; // the original collection length
proxy.length;  //  the paginated length
proxy.getFilteredLength(); // the filtered length
```
