### ISSUE TITLE
Server pagination

### ISSUE THREAD

**Issue by Sinewyk** [jmorrell/backbone.obscura#23]
backbone.obscura kick ass when the collection has everything.

But suppose i'm receiving some pagination from an API. My collection has "right now" 50 models, but there are hundreds more on the API.

Did you ever tackle this generic problem with your library or it wasn't designed with this in mind ?

I'm asking because i'm not seeing anything like that in the docs and i'm not seeing some obvious way I could plug in to fetch incrementally from the server when going next/previous page.

**Comment by jmorrell** [comment]
Unfortunately, I wrote obscura as a way to deal with collections that are fully in-memory. When you have to go out to a server for data there's not a lot you can do, other than update the query parameters and refetch the data, which is going to be dependent on the specific implementation on the backend. Had I wanted to try to support this, I couldn't have done filters, for example.

A project that _does_ try to solve this is [backbone.paginator](https://github.com/backbone-paginator/backbone.paginator) which has a [way to adapt parameters to your backend API](https://github.com/backbone-paginator/backbone.paginator#adapting-to-a-server-api). You can see the trade-off when it comes to filtering in their [FAQ](https://github.com/backbone-paginator/backbone.paginator#faq).

Hope this helps :)

**Comment by Sinewyk** [comment]
Yep it does. i'll have to take a look at carefully mixing your filterable + sortable with their paginator and see how it goes.

Thanks a bunch, now I won't try to fit something that was never meant to fit =D.
