### ISSUE TITLE
Bower.json version doesn't match package.json version as of 1.0.0

### ISSUE THREAD

**Issue by rdworth** [jmorrell/backbone.obscura#24]
Minor noise during bower install

```
bower backbone.obscura#~1.0.0         mismatch Version declared in the json (0.1.7) is different than the resolved one (1.0.0)
```

Too late to fix it for 1.0.0 since that's already tagged+published but maybe something to add to a release checklist (mental or otherwise) for future releases.

**Comment by jmorrell** [comment]
Doh! I thought I had removed that version string from `bower.json` since it's extraneous. Will do on the next release :+1:
